use ratatui::{self, text::Span};

pub const FIRST_BOOT_TEXT_LIST: [&str; 21] = [
    ":: running early hook [udev]",
    "Starting systemd-udevd version 257.7-1-arch",
    ":: running early hook [archiso_pxe_nbd]",
    ":: Triggering uevents...",
    ":: running early hook [memdisk]",
    ":: running early hook [archiso_loop_mnt]",
    ":: running early hook [archiso_pxe_common]",
    ":: running early hook [archiso_pxe_nbd]",
    ":: running early hook [archiso_pxe_http]",
    ":: running early hook [archiso_pxe_nfs]",
    ":: Mounting '/dev/sda1' to '/run/archiso/bootmnt'",
    ":: Device '/dev/sda1' mounted successfully",
    ":: Copying rootfs image to RAM...",
    "",
    ":: Mounting '/dev/loop0' to '/run/archiso/airootfs'",
    ":: Device '/dev/loop0' mounted successfully",
    ":: running late hook [archiso_pxe_common]",
    ":: running cleanup hook [udev]",
    "",
    "",
    "Welcome to Arch Linux!",
];

pub const SECOND_BOOT_TEXT_LIST: [&str; 87] = [
    "[  OK  ] Created slice system‑systemd\\x2dfsck.slice.",
    "          Starting File System Check on /dev/loop0p1...",
    "[  OK  ] Reached target Paths.",
    "[  OK  ] Reached target Remote File Systems.",
    "          Starting Remount Root and Kernel File Systems...",
    "          Mounting Kernel Configuration File System...",
    "[  OK  ] Started Dispatch Password Requests to Console Directory Watch.",
    "[  OK  ] Started Forward Password Requests to Wall Directory Watch.",
    "[  OK  ] Mounted Kernel Configuration File System.",
    "[  OK  ] Finished Remount Root and Kernel File Systems.",
    "          Starting Apply Kernel sysctl variables...",
    "          Starting Load Kernel Modules...",
    "[  OK  ] Finished Apply Kernel sysctl variables.",
    "[  OK  ] Finished Load Kernel Modules.",
    "          Starting Create Static Device Nodes in /dev...",
    "[  OK  ] Finished Create Static Device Nodes in /dev.",
    "          Starting Coldplug All udev Devices...",
    "[  OK  ] Finished Coldplug All udev Devices.",
    "[  OK  ] Reached target Local File Systems (Pre).",
    "          Mounting /tmp (tmpfs)...",
    "          Mounting /run/user/0 (tmpfs)...",
    "[  OK  ] Mounted /tmp.",
    "[  OK  ] Mounted /run/user/0.",
    "          Starting Load/Save Random Seed...",
    "          Starting Journal Service...",
    "[  OK  ] Started Journal Service.",
    "[  OK  ] Finished Load/Save Random Seed.",
    "          Starting Flush Journal to Persistent Storage...",
    "[  OK  ] Finished Flush Journal to Persistent Storage.",
    "          Starting Create Volatile Files and Directories...",
    "[  OK  ] Finished Create Volatile Files and Directories.",
    "          Starting Update UTMP about System Boot/Shutdown...",
    "[  OK  ] Finished Update UTMP about System Boot/Shutdown.",
    "[  OK  ] Reached target System Initialization.",
    "          Starting Network Manager...",
    "          Starting D‑Bus System Message Bus...",
    "[  OK  ] Listening on D‑Bus System Message Bus Socket.",
    "[  OK  ] Started D‑Bus System Message Bus.",
    "[  OK  ] Started Network Manager.",
    "          Starting Authorization Manager...",
    "[  OK  ] Started Authorization Manager.",
    "          Starting Accounts Service...",
    "          Starting Login Service...",
    "[  OK  ] Started Login Service.",
    "[  OK  ] Started Accounts Service.",
    "          Starting Getty on tty1...",
    "[  OK  ] Started Getty on tty1.",
    "[  OK  ] Reached target Multi‑User System.",
    "          Starting Arch keyring initialization...",
    "[  OK  ] Finished Arch keyring initialization.",
    "          Starting Pacman keyring refresh...",
    "[  OK  ] Finished Pacman keyring refresh.",
    "          Starting Reflector simple service...",
    "[  OK  ] Finished Reflector simple service.",
    "          Starting Network Time Synchronization...",
    "[  OK  ] Started Network Time Synchronization.",
    "[  OK  ] Reached target Time Synchronization.",
    "          Starting Authorization Policy Kit Daemon...",
    "[  OK  ] Started Authorization Policy Kit Daemon.",
    "          Mounting FUSE Control File System...",
    "[  OK  ] Mounted FUSE Control File System.",
    "[  OK  ] Reached target Sound Card Initialization.",
    "          Starting Hostname Service...",
    "[  OK  ] Started Hostname Service.",
    "[  OK  ] Reached target Bluetooth Support.",
    "          Starting Bluetooth Service...",
    "[  OK  ] Started Bluetooth Service.",
    "          Starting CUPS Scheduler...",
    "[  OK  ] Started CUPS Scheduler.",
    "          Starting Login Prompts...",
    "[  OK  ] Started Login Prompts.",
    "          Mounting /boot/efi...",
    "[  OK  ] Mounted /boot/efi.",
    "[  OK  ] Listening on UUID daemon activation socket.",
    "[  OK  ] Listening on Avahi mDNS/DNS-SD Stack Activation Socket.",
    "          Starting Authorization Service Watchdog...",
    "[  OK  ] Started Authorization Service Watchdog.",
    "          Starting System Logging Service...",
    "[  OK  ] Started System Logging Service.",
    "[  OK  ] Listening on GnuPG cryptographic agent and passphrase entry.",
    "          Starting Modem Manager...",
    "[  OK  ] Started Modem Manager.",
    "          Starting Avahi mDNS/DNS-SD Stack...",
    "[  OK  ] Started Avahi mDNS/DNS-SD Stack.",
    "[  OK  ] Reached target Graphical Interface (gnome‑keyring disabled on live ISO).",
    "          Starting TUI Boot Splash...",
    "[  OK  ] Started TUI Boot Splash.",
];
